spring:
  application:
    name: novel-factory
  datasource:
    url: jdbc:mysql://localhost:3306/novel_factory
    username: novel_factory
    password: novel_factory
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
