package com.novelfactory.common.api;

public enum ErrorCode {
  VALIDATION_ERROR,
  BOOK_CREATE_FAILED,
  BOOK_NOT_FOUND,
  PIPELINE_TASK_CREATE_FAILED,
  PIPELINE_TASK_NOT_FOUND,
  AGENT_EXECUTION_FAILED,
  INVALID_GENERATION_TARGET,
  LLM_CALL_FAILED,
  ADDICTION_CANVAS_GENERATION_FAILED,
  WORLD_SETTING_GENERATION_FAILED,
  CHARACTER_PROFILE_GENERATION_FAILED,
  PLAN_CARD_GENERATION_FAILED,
  OUTLINE_GENERATION_FAILED,
  ADDICTION_CANVAS_NOT_FOUND,
  WORLD_SETTING_NOT_FOUND,
  CHARACTER_PROFILE_NOT_FOUND,
  PLAN_CARD_NOT_FOUND,
  OUTLINE_DRAFT_NOT_FOUND,
  INVALID_TASK_STATE_TRANSITION,
  INTERNAL_ERROR
}
