package com.novelfactory.common.api;

public enum ErrorCode {
  VALIDATION_ERROR,
  BOOK_CREATE_FAILED,
  BOOK_NOT_FOUND,
  PIPELINE_TASK_CREATE_FAILED,
  PIPELINE_TASK_NOT_FOUND,
  AGENT_EXECUTION_FAILED,
  INTERNAL_ERROR
}
