package com.novelfactory.pipeline.model;

public enum PipelineTaskEvent {
  START,
  ADDICTION_CANVAS_SUCCEEDED,
  WORLD_SETTING_SUCCEEDED,
  CHARACTER_PROFILE_SUCCEEDED,
  PLAN_CARD_SUCCEEDED,
  OUTLINE_REQUIRED,
  OUTLINE_SUCCEEDED,
  COMPLETE_WITHOUT_OUTLINE,
  COMPLETE,
  STEP_FAILED
}
